# Generated by Django 4.1.3 on 2023-02-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_options_rename_state_task_task_is_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tasks", to="todo.tag"
            ),
        ),
    ]
