# Generated by Django 4.1.6 on 2023-02-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["state_task", "create_datetime"]},
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name="task",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="task.tag"),
        ),
    ]
