# Generated by Django 4.1.6 on 2023-02-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_options_alter_tag_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["state_task", "-create_datetime"]},
        ),
    ]
