# Generated by Django 4.1.6 on 2023-02-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_remove_task_tags_task_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["state_task", "create_datetime"]},
        ),
    ]
