# Generated by Django 4.1.6 on 2023-02-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
