# Generated by Django 4.1.6 on 2023-02-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_alter_task_create_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=63),
        ),
    ]
