# Generated by Django 4.1.3 on 2023-02-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_task", "-create_datetime"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="state_task",
            new_name="is_task",
        ),
    ]
